#!/bin/bash
B="\e[1;44m"
FT="\e[1;30m\e[1m"
R="\e[0m"
S="\e[100m"
A="\e[1;35m"
dir=$(pwd)
term=$(ps -h -o comm -p $PPID)
function terminals {
clear
echo ""
echo -e "$FT    $B                                    $R"
echo -e "$FT    $B   Las terminales soportadas son:   $S $R"
echo -e "$FT    $B                                    $S $R"
echo -e "$FT     $S                                    $R"
echo -e ""
echo -e "$FT    $B                    $R"
echo -e "$FT    $B   Tilix            $S $R"
echo -e "$FT    $B   Konsole          $S $R"
echo -e "$FT    $B   Terminator       $S $R"
echo -e "$FT    $B   Gnome Terminal   $S $R"
echo -e "$FT    $B   Xfce Terminal    $S $R"
echo -e "$FT    $B   Alacritty        $S $R"
echo -e "$FT    $B   Kitty            $S $R"
echo -e "$FT    $B                    $S $R"
echo -e "$FT     $S                    $R"
echo ""
}
function tanks {
clear
echo ""
echo -e "$FT    $B                                $R"
echo -e "$FT    $B   Gracias por instalar ymenu   $S $R"
echo -e "$FT    $B                                $S $R"
echo -e "$FT     $S                                $R"
echo ""
}
function copy {
rm -r $HOME/.ymenu
mkdir $HOME/.ymenu && cp -r $dir/spanish $HOME/.ymenu && sudo cp -r $HOME/.ymenu/spanish/ymenu /usr/bin
}
function editor {
view=$(ls $HOME/.config/ymenuEditor)
if [[ $view == ymenuEditor ]]; then
echo ""
elif [[ -z $view ]]; then
touch $HOME/.config/ymenuEditor &&
echo 'nano' >> $HOME/.config/ymenuEditor
fi
}
term=$(ps -h -o comm -p $PPID)
if [[ $term == tilix ]]; then
	copy
	echo 'export rt="$HOME/.ymenu/spanish"
	export term="tilix"
	prmt=$1
	sh "$1"' >> $HOME/.ymenu/spanish/start
	editor
	tanks && sleep 3 && exit
elif [[ $term == konsole ]]; then
	copy
	echo 'export rt="$HOME/.ymenu/spanish"
		export term="konsole"
		prmt=$1
		sh "$1"' >> $HOME/.ymenu/spanish/start
	editor
		tanks && source ~/.zshrc
elif [[ $term == terminator ]]; then
	copy
	echo 'export rt="$HOME/.ymenu/spanish"
		export term="terminator"
		prmt=$1
		sh "$1"' >> $HOME/.ymenu/spanish/start
	editor
		tanks && sleep 3 && exit
elif [[ $term == gnome-terminal ]]; then
	copy
	echo 'export rt="$HOME/.ymenu/spanish"
		export term="gnome-terminal"
		prmt=$1
		sh "$1"' >> $HOME/.ymenu/spanish/start
	editor
		tanks && sleep 3 && exit
elif [[ $term == xfce4-terminal ]]; then
	copy
	echo 'export rt="$HOME/.ymenu/spanish"
		export term="tilix"
		prmt=$1
		sh "$1"' >> $HOME/.ymenu/spanish/start
	editor
		tanks && sleep 3 && exit
elif [[ $term == alacritty ]]; then
	copy
	echo 'export rt="$HOME/.ymenu/spanish"
		export term="alacritty"
		prmt=$1
		sh "$1"' >> $HOME/.ymenu/spanish/start
	editor
		tanks && sleep 3 && exit
elif [[ $term == kitty ]]; then
	copy
	echo 'export rt="$HOME/.ymenu/spanish"
		export term="tilix"
		prmt=$1
		sh "$1"' >> $HOME/.ymenu/spanish/start
	editor
		tanks && sleep 3 && exit
else
	terminals && sleep 3 && exit
fi

