#!/bin/bash
while true; do
men=$(yad --on-top --list --borders=50 --sticky --undecorated --width=370 --height=250 --no-buttons --title="Menu" --column="" \
'[ ◀ Volver al principio ]' \
'[ Apagar ]' \
'[ Reiniciar ]' \
'[ Salir de sesion ]' )
var=$?
#echo $var
#echo $men
if [[ $var == 0 ]]; then
	if [[ $men == "[ ◀ Volver al principio ]|" ]]; then
		sh $rt/start $rt/ymenu2
		break
	elif [[ $men == "[ Apagar ]|" ]]; then
		shutdown 0
		break
	elif [[ $men == "[ Reiniciar ]|" ]]; then
		reboot
		break
	elif [[ $men == "[ Salir de sesion ]|" ]]; then
		kill -9 -1
		break
	fi
elif [[ $var == 252 ]]; then
	break
fi
done
