#!/bin/bash
while true; do
men=$(yad --on-top --list --borders=50 --sticky --undecorated --width=480 --height=275 --no-buttons --title="Menu" --column="" \
'[ ◀ Volver al principio ]' \
'[ Abrir el reloj ]' \
'[ Consultar el hisorial de la shell ]' \
'[ Ejecutar scrcpy ]' \
'[ Erramienta de scripts ]' )
var=$?
#echo $var
#echo $men
if [[ $var == 0 ]]; then
	if [[ $men == "[ ◀ Volver al principio ]|" ]]; then
		sh $rt/start $rt/ymenu2
		break
	elif [[ $men == "[ Consultar el hisorial de la shell ]|" ]]; then
		$term -e sh $rt/start $rt/hist &
		break
	elif [[ $men == "[ Abrir el reloj ]|" ]]; then
		$term -e tty-clock &
		break
	elif [[ $men == "[ Ejecutar scrcpy ]|" ]]; then
		$term -e scrcpy &
		break
	elif [[ $men == "[ Erramienta de scripts ]|" ]]; then
		$term -e sh $rt/start $rt/texto &
		break
	fi
elif [[ $var == 252 ]]; then
	break
fi
done
