#!/bin/bash
B="\e[1;44m"
FT="\e[1;30m\e[1m"
R="\e[0m"
S="\e[100m"
PR="\e[1;34m"
function help {
echo -e "$FT    $B          [  1.0  ]         $R"
echo -e "$FT    $B -rR  Para correr ymenu     $S $R"
echo -e "$FT    $B -dD  Para eliminiar ymenu  $S $R"
echo -e "$FT    $B -uU  Para actualizar ymenu $S $R"
echo -e "$FT    $B                             $S $R"
echo -e "$FT     $S                             $R"
}
function run {
	sh $HOME/.ymenu/spanish/start $HOME/.ymenu/spanish/ymenu2
}
function del {
	sudo rm -r $HOME/.ymenu
	sudo rm -r /usr/bin/ymenu
}
function upt {
	echo "No se ha definido espera a la proxima actualizacion"
}
prompt=$1
if [[ -z $1 ]]; then help
elif [[ $1 == -r ]]; then run
elif [[ $1 == -R ]]; then run
elif [[ $1 == -d ]]; then del
elif [[ $1 == -D ]]; then del
elif [[ $1 == -h ]]; then help
elif [[ $1 == -H ]]; then help
elif [[ $1 == --help ]]; then help
else help
fi
