#!/bin/bash
while true; do
men=$(yad --on-top --list --borders=50 --sticky --undecorated --width=405 --height=275 --no-buttons --title="Menu" --column="" \
'[ ◀ Back to the top ]' \
'[ Open the clock ]' \
'[ Consult the shell history ]' \
'[ Run scrcpy ]' \
'[ Scripting tool ]' )
var=$?
#echo $var
#echo $men
if [[ $var == 0 ]]; then
	if [[ $men == "[ ◀ Back to the top ]|" ]]; then
		sh $rt/start $rt/ymenu2
		break
	elif [[ $men == "[ Consult the shell history ]|" ]]; then
		$term -e sh $rt/start $rt/hist &
		break
	elif [[ $men == "[ Open the clock ]|" ]]; then
		$term -e tty-clock &
		break
	elif [[ $men == "[ Run scrcpy ]|" ]]; then
		$term -e scrcpy &
		break
	elif [[ $men == "[ Scripting tool ]|" ]]; then
		$term -e sh $rt/start $rt/texto &
		break
	fi
elif [[ $var == 252 ]]; then
	break
fi
done
