#!/bin/bash
while true; do
men=$(yad --on-top --list --borders=50 --sticky --undecorated --width=335 --height=250 --no-buttons --title="Menu" --column="  ( Only BSPWM )" \
'[ ◀ Back to the top ]' \
'[ Floating ]' \
'[ Fullscreen ]' \
'[ Tiling ]' )
var=$?
#echo $var
#echo $men
if [[ $var == 0 ]]; then
	if [[ $men == "[ ◀ Back to the top ]|" ]]; then
		sh $rt/start $rt/ymenu2
		break
	elif [[ $men == "[ Floating ]|" ]]; then
		bspc rule -a '*' state=floating &
		break
	elif [[ $men == "[ Fullscreen ]|" ]]; then
		bspc rule -a '*' state=fullscreen &
		break
	elif [[ $men == "[ Tiling ]|" ]]; then
		bspc rule -a '*' state=tiled &
		break
	fi
elif [[ $var == 252 ]]; then
	break
fi
done
