#!/bin/bash
while true; do
men=$(yad --on-top --list --borders=50 --sticky --undecorated --width=345 --height=230 --no-buttons --title="Menu" --column="" \
'[ Execute applets ▶ ]' \
'[ Shutdown options ▶ ]' \
'[ Layout options ▶ ]' )
var=$?
#echo $var
#echo $men
if [[ $var == 0 ]]; then
	if [[ $men == "[ Execute applets ▶ ]|" ]]; then
		sh $rt/start $rt/yapplet
		break
	elif [[ $men == "[ Shutdown options ▶ ]|" ]]; then
		sh $rt/start $rt/yapagado
		break
	elif [[ $men == "[ Layout options ▶ ]|" ]]; then
		sh $rt/start $rt/ybspc
		break
	fi
elif [[ $var == 252 ]]; then
	break
fi
done
